### PR TITLE
Add support of Mul ONNX op

### PR DESCRIPTION
**Pull request by take-cheeze**
rel: #15

Though still fails in onnxruntime in tiny yolo v2...

### CODE REVIEW

**Comment by notogawa** [comment]
Thank you for PR

nnoir is a format for representing a statically sized computation graph. [tiny_yolo_v2 in onnx model zoo](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov2) has statically unknown batch size. Before convert using `onnx2nnoir`, try to edit model to fix size, like this.
```Python
import onnx
model = onnx.load('Model.onnx')
for x in model.graph.input:
    if x.type.HasField('tensor_type'):
        for dim in x.type.tensor_type.shape.dim:
            if dim.HasField('dim_param'):
                dim.ClearField('dim_param')
                dim.dim_value = 1
onnx.save(model, 'Model_fixed.onnx')
```


`MulConstant` is operation for `(dynamic)tensor * (constant)scalar`. `Scale` operation is suitable for this `(dynamic)tensor * (constant)tensor` case. (This distinction is from historical one)

**Comment by take-cheeze** [comment]
Thanks for the advice.
It seems CI isn't running on my PR. Is it possible to run it?

**Comment by notogawa** [comment]
"Build forked pull requests" will now be enabled.

**Comment by take-cheeze** [comment]
@notogawa Thanks!

**Comment by notogawa** [comment]
https://github.com/Idein/nnoir/pull/52 merged.

**Pull request closed without merging**
